name: "Greetings"
description: "Greetings using Docker"

inputs:
  greeting:
    description: Greeting word
    required: true
    default: "Hei"
  name:
    description: Who to greet
    required: true
    default: "my friend"

outputs:
  greeting-text:
    description: Greeting text
    value: ${{ steps.generate-output-step.outputs.output}}
    

runs:
  using: composite
  steps:
    - name: Show greeting text
      run: echo '${{ inputs.greeting}}, ${{inputs.name }}'
      shell: bash
    - name: Generate output
      env: {OUTPUT: '${{ inputs.greeting }}, ${{ inputs.name }}'}
      id: generate-output-step
      run: echo 'output=$OUTPUT >> $GITHUB_OUTPUT'
      shell: bash
