name: Demo GitHub Actions Events

env:
  level: workflow level
  GREETING_WORD: Hello

on:
  # Webhook events (https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows)
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches: [main]
  issues:
    types:
      - opened
      - closed

  
  # Scheduled events
  schedule:
    - cron: 0 9 * * *
      timezone: Europe/Oslo
    - cron: 1 12 * * 1
  # Manual events
  workflow_dispatch:
    #inputs: # Will show up in a form on GitHub
    inputs:
      feeling_good:
        type: boolean
        description: Feeling good
  repository_dispatch:
    types:
      - customEvent
      - sdsf


jobs:
  Greeting:
    env:
      level: job level
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo ${{ env.GREETING_WORD }}
      - name: Run if feeling good
        if: ${{ inputs.feeling_good}}
        run: echo "Great."
      - name: Level
        run: echo ${{ env.level }}
      - name: Level
        env: {level: step level}
        run: echo ${{ env.level }}
        
  Greeting2:
    runs-on: windows-latest
    steps:
      - name: Say hello
        run: echo ${{ env.GREETING_WORD }}
      - name: Run if feeling good
        if: ${{ inputs.feeling_good}}
        run: echo "Great."
      - name: Level
        run: echo ${{ env.level }}    
  
  contexts:
    name: Show context
    runs-on: ubuntu-slim
    steps:
      - name: runner
        run: echo '${{ toJson(runner) }}'
      - name: github
        run: echo '${{ toJson(github) }}'
      

run-name: Demo action triggered by ${{ github.event_name}}
